#pragma once
static const char NETWORK_PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IPv4 · 4VRS</title><style>body{font:17px system-ui;max-width:640px;margin:32px auto;padding:0 20px;background:#101820;color:#edf4ff}a{color:#7ce0ff}label{display:block;margin:16px 0}input,select,button{box-sizing:border-box;width:100%;font:inherit;padding:12px;margin-top:6px}button{background:#087cba;color:white;border:0}button:disabled{opacity:.5}small{color:#bacbde}[hidden]{display:none}#status{white-space:pre-wrap}</style><a href="/">← Главная</a><h1>Настройки IPv4</h1><p>DHCP получает адрес автоматически. Для статического адреса выберите свободный IP вашей сети.</p><form id="network"><label>Режим адресации<select id="mode"><option value="dhcp">DHCP</option><option value="static">Static IPv4</option></select></label><div id="addresses" hidden><label>IP<input id="ip" maxlength="15" inputmode="decimal"></label><label>Маска подсети<input id="mask" maxlength="15" inputmode="decimal"></label><label>Шлюз<input id="gateway" maxlength="15" inputmode="decimal"></label><label>Основной DNS<input id="dns1" maxlength="15" inputmode="decimal"></label><label>Резервный DNS<input id="dns2" maxlength="15" inputmode="decimal"></label><small>Шлюз и DNS можно оставить пустыми для изолированной сети. Для обновлений GitHub нужны доступ в интернет и рабочий DNS.</small></div><p>После применения откройте эту страницу по новому адресу и подтвердите связь в течение 3 минут. Без подтверждения вернутся прежние настройки. Во время проверки доступна точка настройки Wi-Fi.</p><button id="apply" disabled>Применить и проверить</button></form><p id="status" role="status"></p><p><a id="target" hidden>Открыть новый адрес</a></p><button id="confirm" hidden>Подтвердить подключение</button><script>
const $=id=>document.getElementById(id),token='__TOKEN__',fields=['ip','mask','gateway','dns1','dns2'];let busy=false;
function visibility(){$('addresses').hidden=$('mode').value!=='static'}$('mode').onchange=visibility;
async function load(){let r=await fetch('/network/config',{cache:'no-store'});if(!r.ok)throw Error();let c=await r.json();$('mode').value=c.static?'static':'dhcp';for(let f of fields)$(f).value=c[f]||c['current_'+f]||'';visibility();$('apply').disabled=c.trial;$('confirm').hidden=!c.can_confirm;$('status').textContent=c.trial?'Ожидается подтверждение. Осталось секунд: '+c.remaining_s:'Текущий адрес: '+c.current_ip}
load().catch(()=>$('status').textContent='Не удалось прочитать настройки. Обновите страницу.');
async function send(b){let r=await fetch('/network/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,...b})});if(!r.ok)throw Error(await r.text());return r.json()}
$('network').onsubmit=async e=>{e.preventDefault();if(busy||$('apply').disabled)return;busy=true;$('apply').disabled=true;try{let b={static:$('mode').value==='static'};for(let f of fields)b[f]=$(f).value.trim();await send(b);$('status').textContent='Проверка началась. Откройте новый адрес и подтвердите подключение в течение 3 минут.';if(b.static&&/^\d{1,3}(\.\d{1,3}){3}$/.test(b.ip)){$('target').href='http://'+b.ip+'/network';$('target').hidden=false}else{$('status').textContent+=' DHCP: найдите адрес в роутере или через точку настройки Wi-Fi.'}setTimeout(()=>load().catch(()=>{}),5000)}catch(e){$('status').textContent=e.message;$('apply').disabled=false}finally{busy=false}};
$('confirm').onclick=async()=>{if(busy)return;busy=true;$('confirm').disabled=true;try{await send({confirm:true});await load();$('status').textContent='Настройки сети сохранены.'}catch(e){$('status').textContent=e.message}finally{busy=false;$('confirm').disabled=false}};
</script></html>)HTML";
