#pragma once
// Central web UI dictionary. Only trusted templates pass through this function.
inline String localizeWeb(String page) {
  if(!WebSettings::english())return page;
  page.replace("lang=\"ru\"","lang=\"en\"");
  page.replace("Пустой пароль сохраняет текущий. Логин: 1–32 символа, пароль: 1–64. Используйте латинские буквы, цифры и символы без пробелов; двоеточие в логине недопустимо.","Leave the password empty to keep it. Username: 1\u201332 characters; password: 1\u201364. Use ASCII letters, numbers and symbols without spaces; no colon in the username.");
  page.replace("Эти данные используются только для web-входа. Пароли OTA, Wi-Fi и MQTT не изменяются.","These credentials are only for web sign-in. OTA, Wi-Fi and MQTT passwords remain unchanged.");
  page.replace("Точка настройки отключена. Вернитесь в локальную сеть и откройте показанный IP.","The setup access point is off. Rejoin your LAN and open the displayed IP address.");
  page.replace("Первый канал HA: до 12 сущностей, по три на странице. Без данных остаётся встроенная заставка.","Display up to 12 Home Assistant entities, three per page. The default artwork is shown until data arrives.");
  page.replace("Нет связи. Проверьте сохранённые настройки после подключения.","Connection lost. Check the saved settings after reconnecting.");
  page.replace("Выберите сеть 2,4 ГГц. Для скрытой сети введите имя вручную.","Choose a 2.4 GHz network. Enter the name manually for a hidden network.");
  page.replace("Точка настройки выключится после 15 секунд устойчивой связи.","The setup access point will turn off after 15 seconds of stable connection.");
  page.replace("Вводится только в нашей интеграции HA. Не публикуйте ключ.","Enter this key in the 4VRS Display HA integration. Keep it private.");
  page.replace("Сохранено. При следующем запросе войдите с новыми данными.","Saved. Sign in with the new credentials on the next request.");
  page.replace("Связь потеряна. Откройте настройки и проверьте сохранение.","Connection lost. Open settings to check whether the changes were saved.");
  page.replace("Связь с платой потеряна. Проверьте подключение к её Wi-Fi.","Connection to the device was lost. Check its Wi-Fi connection.");
  page.replace("Настройки сохранены. Подключение выполняется в фоне.","Settings saved. Connecting in the background.");
  page.replace("Не удалось прочитать настройки. Обновите страницу.","Could not read settings. Reload this page.");
  page.replace("Принимать данные Home Assistant через MQTT","Receive Home Assistant data via MQTT");
  page.replace("Подключение к брокеру и Home Assistant","Connect to a broker and Home Assistant");
  page.replace("CA-сертификат PEM (обязателен для TLS)","CA certificate in PEM format (required for TLS)");
  page.replace("Не удалось обновить сведения о сети.","Could not refresh network information.");
  page.replace("Посмотреть изображение по умолчанию","View the default image");
  page.replace("Поиск не завершился. Повторите.","Scan did not finish. Try again.");
  page.replace("Пусто — сохранить действующий","Leave empty to keep the current password");
  page.replace("Сеть сохранена. Подключаемся…","Network saved. Connecting\u2026");
  page.replace("TLS с проверкой сертификата","TLS with certificate verification");
  page.replace("Версия, сеть и диагностика","Version, network and diagnostics");
  page.replace("Лицензия собственного кода","Own code license");
  page.replace("Удалить сохранённый пароль","Delete the saved password");
  page.replace("Последний код отключения: ","Last disconnect reason: ");
  page.replace("Управление вашим дисплеем","Manage your display");
  page.replace("Подключение интеграции HA","Pair with the HA integration");
  page.replace("Ошибка чтения настроек","Could not read settings");
  page.replace("Повторите новый пароль","Confirm new password");
  page.replace("Точка настройки Wi-Fi","Wi-Fi setup access point");
  page.replace("Обновление по воздуху","Over-the-air updates");
  page.replace("Подробная диагностика","Detailed diagnostics");
  page.replace("Сохранить подключение","Save connection");
  page.replace("Настройки интерфейса","Interface settings");
  page.replace("Пароли не совпадают.","Passwords do not match.");
  page.replace("Сеть ещё не выбрана.","No network selected yet.");
  page.replace("Открыть устройство: ","Open device: ");
  page.replace("Встроенная заставка","Default artwork");
  page.replace("Язык и данные входа","Language and sign-in");
  page.replace("Нет связи с модулем","Cannot reach the device");
  page.replace("Открыть настройки","Open settings");
  page.replace("Чтение состояния…","Reading status\u2026");
  page.replace("Ключ сопряжения:","Pairing key:");
  page.replace("Настройки · 4VRS","Settings \u00b7 4VRS");
  page.replace("Язык интерфейса","Interface language");
  page.replace("Имя сети (SSID)","Network name (SSID)");
  page.replace("Подключаемся к ","Connecting to ");
  page.replace("Найдено сетей: ","Networks found: ");
  page.replace("Настройки MQTT","MQTT settings");
  page.replace("Найденные сети","Available networks");
  page.replace("Адрес брокера","Broker address");
  page.replace("Выберите сеть","Choose a network");
  page.replace("Подключено к ","Connected to ");
  page.replace("Пользователь","Username");
  page.replace("Новый пароль","New password");
  page.replace("Поиск сетей…","Scanning networks\u2026");
  page.replace("Пароль MQTT","MQTT password");
  page.replace("Диагностика","Diagnostics");
  page.replace("Пароль сети","Network password");
  page.replace(" · открытая"," \u00b7 open");
  page.replace("Устройство","Device");
  page.replace("Найти сети","Scan networks");
  page.replace("Подключить","Connect");
  page.replace("Выключена","Disabled");
  page.replace("Состояние","Status");
  page.replace("Сохранить","Save");
  page.replace("О модуле","About");
  page.replace("Прошивка","Firmware");
  page.replace("IP-адрес","IP address");
  page.replace("Включена","Enabled");
  page.replace("Главная","Home");
  page.replace("Логин","Username");
  page.replace("Порт","Port");
  return page;
}
