#pragma once
// Central web UI dictionary. Only trusted templates pass through this function.
inline String localizeWeb(String page) {
  if(!WebSettings::english())return page;
  page.replace("Проверьте IP, маску, шлюз и DNS. Подсеть точки настройки 192.168.4.0/24 зарезервирована.","Check IP, mask, gateway and DNS. Setup subnet 192.168.4.0/24 is reserved.");
  page.replace("После применения откройте эту страницу по новому адресу и подтвердите связь в течение 3 минут. Без подтверждения вернутся прежние настройки. Во время проверки доступна точка настройки Wi-Fi.","After applying, open this page at the new address and confirm connectivity within 3 minutes. Without confirmation, the previous settings return. Setup Wi-Fi stays available during the trial.");
  page.replace("Шлюз и DNS можно оставить пустыми для изолированной сети. Для обновлений GitHub нужны доступ в интернет и рабочий DNS.","Gateway and DNS may be empty for an isolated network. GitHub updates require internet access and working DNS.");
  page.replace("DHCP получает адрес автоматически. Для статического адреса выберите свободный IP вашей сети.","DHCP obtains an address automatically. For static addressing, choose an unused IP on your network.");
  page.replace("Проверка началась. Откройте новый адрес и подтвердите подключение в течение 3 минут.","Trial started. Open the new address and confirm connectivity within 3 minutes.");
  page.replace(" DHCP: найдите адрес в роутере или через точку настройки Wi-Fi."," DHCP: find the address in your router or through setup Wi-Fi.");
  page.replace("Ожидается подтверждение. Осталось секунд: ","Awaiting confirmation. Seconds remaining: ");
  page.replace("Настройки сети сохранены.","Network settings saved.");
  page.replace("Текущий адрес: ","Current address: ");
  page.replace("Настройки IPv4","IPv4 settings");
  page.replace("DHCP, IP, маска, шлюз и DNS","DHCP, IP, subnet mask, gateway and DNS");
  page.replace("Режим адресации","Address mode");
  page.replace("Маска подсети","Subnet mask");
  page.replace("Шлюз","Gateway");
  page.replace("Основной DNS","Primary DNS");
  page.replace("Резервный DNS","Secondary DNS");
  page.replace("Применить и проверить","Apply and test");
  page.replace("Открыть новый адрес","Open new address");
  page.replace("Подтвердить подключение","Confirm connection");
  page.replace("Название и значок перед страницами комнаты. При отключении название остаётся в заголовке, комнаты не смешиваются.","Show the room name and icon before its pages. When disabled, the header keeps the room name and rooms stay separate.");
  page.replace("Не удалось сохранить настройки экрана. Попробуйте ещё раз.","Could not save display settings. Please retry.");
  page.replace("Настройки экрана сохранены.","Display settings saved.");
  page.replace("Сохранить настройки экрана","Save display settings");
  page.replace("Показывать заставки комнат","Show room covers");
  page.replace("<h2>Экран</h2>","<h2>Display</h2>");
  page.replace("Ответ не получен. Если SDO/MISO не подключён, это ожидаемо и не означает неисправность дисплея. Иначе проверьте соединение и питание.","No response received. If SDO/MISO is not connected, this is expected and does not mean the display is faulty. Otherwise, check wiring and power.");
  page.replace("Проверка связи с контроллером дисплея по SDO/MISO (GPIO19). Для вывода изображения этот провод не нужен.","Check communication with the display controller over SDO/MISO (GPIO19). This wire is not required to show images.");
  page.replace("Ответ контроллера не подтверждает исправность матрицы и подсветки: изображение нужно оценить визуально.","A controller response does not verify the panel or backlight: inspect the image visually.");
  page.replace("Не удалось выполнить проверку. Проверьте связь с модулем и повторите попытку.","Could not run the check. Check the device connection and try again.");
  page.replace("Контроллер дисплея отвечает. Повторные чтения регистров совпадают.","The display controller responds. Repeated register readings match.");
  page.replace("Данные ещё не прочитаны. Повторите проверку после запуска дисплея.","No readings yet. Try again after the display starts.");
  page.replace("Ответы различаются. Проверьте соединения SPI и питание дисплея.","Readings differ. Check the SPI connections and display power.");
  page.replace("Нажмите кнопку для проверки.","Press the button to run a check.");
  page.replace("Проверяем связь с дисплеем…","Checking display communication...");
  page.replace("Данные дисплея (JSON)","Display data (JSON)");
  page.replace("Проверить дисплей","Check display");
  page.replace("Проверка дисплея","Display check");
  page.replace("Регистры дисплея","Display registers");
  page.replace("lang=\"ru\"","lang=\"en\"");
  page.replace("Пустой пароль сохраняет текущий. Логин: 1–32 символа, пароль: 1–64. Используйте латинские буквы, цифры и символы без пробелов; двоеточие в логине недопустимо.","Leave the password empty to keep it. Username: 1\u201332 characters; password: 1\u201364. Use ASCII letters, numbers and symbols without spaces; no colon in the username.");
  page.replace("Эти данные используются только для web-входа. Пароли OTA, Wi-Fi и MQTT не изменяются.","These credentials are only for web sign-in. OTA, Wi-Fi and MQTT passwords remain unchanged.");
  page.replace("Точка настройки отключена. Вернитесь в локальную сеть и откройте показанный IP.","The setup access point is off. Rejoin your LAN and open the displayed IP address.");
  page.replace("Первый канал HA: до 20 сущностей, по три на странице. Без данных остаётся встроенная заставка.","Display up to 20 Home Assistant entities, three per page. The default artwork is shown until data arrives.");
  page.replace("Нет связи. Проверьте сохранённые настройки после подключения.","Connection lost. Check the saved settings after reconnecting.");
  page.replace("Выберите сеть 2,4 ГГц. Для скрытой сети введите имя вручную.","Choose a 2.4 GHz network. Enter the name manually for a hidden network.");
  page.replace("Точка настройки выключится после 15 секунд устойчивой связи.","The setup access point will turn off after 15 seconds of stable connection.");
  page.replace("Вводится только в нашей интеграции HA. Не публикуйте ключ.","Enter this key in the 4VRS Display HA integration. Keep it private.");
  page.replace("Сохранено. При следующем запросе войдите с новыми данными.","Saved. Sign in with the new credentials on the next request.");
  page.replace("Связь потеряна. Откройте настройки и проверьте сохранение.","Connection lost. Open settings to check whether the changes were saved.");
  page.replace("Связь с платой потеряна. Проверьте подключение к её Wi-Fi.","Connection to the device was lost. Check its Wi-Fi connection.");
  page.replace("Настройки сохранены. Подключение выполняется в фоне.","Settings saved. Connecting in the background.");
  page.replace("Не удалось прочитать настройки. Обновите страницу.","Could not read settings. Reload this page.");
  page.replace("Принимать данные Home Assistant через MQTT","Receive Home Assistant data via MQTT");
  page.replace("Подключение к брокеру и Home Assistant","Connect to a broker and Home Assistant");
  page.replace("CA-сертификат PEM (обязателен для TLS)","CA certificate in PEM format (required for TLS)");
  page.replace("Не удалось обновить сведения о сети.","Could not refresh network information.");
  page.replace("Посмотреть изображение по умолчанию","View the default image");
  page.replace("Поиск не завершился. Повторите.","Scan did not finish. Try again.");
  page.replace("Пусто — сохранить действующий","Leave empty to keep the current password");
  page.replace("Сеть сохранена. Подключаемся…","Network saved. Connecting\u2026");
  page.replace("TLS с проверкой сертификата","TLS with certificate verification");
  page.replace("Версия, сеть и диагностика","Version, network and diagnostics");
  page.replace("Лицензия собственного кода","Own code license");
  page.replace("Удалить сохранённый пароль","Delete the saved password");
  page.replace("Последний код отключения: ","Last disconnect reason: ");
  page.replace("Управление вашим дисплеем","Manage your display");
  page.replace("Подключение интеграции HA","Pair with the HA integration");
  page.replace("Ошибка чтения настроек","Could not read settings");
  page.replace("Повторите новый пароль","Confirm new password");
  page.replace("Точка настройки Wi-Fi","Wi-Fi setup access point");
  page.replace("Обновление по воздуху","Over-the-air updates");
  page.replace("Подробная диагностика","Detailed diagnostics");
  page.replace("Сохранить подключение","Save connection");
  page.replace("Настройки интерфейса","Interface settings");
  page.replace("Пароли не совпадают.","Passwords do not match.");
  page.replace("Сеть ещё не выбрана.","No network selected yet.");
  page.replace("Открыть устройство: ","Open device: ");
  page.replace("Встроенная заставка","Default artwork");
  page.replace("Язык и данные входа","Language and sign-in");
  page.replace("Нет связи с модулем","Cannot reach the device");
  page.replace("Открыть настройки","Open settings");
  page.replace("Чтение состояния…","Reading status\u2026");
  page.replace("Ключ сопряжения:","Pairing key:");
  page.replace("Настройки · 4VRS","Settings \u00b7 4VRS");
  page.replace("Язык интерфейса","Interface language");
  page.replace("Имя сети (SSID)","Network name (SSID)");
  page.replace("Подключаемся к ","Connecting to ");
  page.replace("Найдено сетей: ","Networks found: ");
  page.replace("Настройки MQTT","MQTT settings");
  page.replace("Найденные сети","Available networks");
  page.replace("Адрес брокера","Broker address");
  page.replace("Выберите сеть","Choose a network");
  page.replace("Подключено к ","Connected to ");
  page.replace("Пользователь","Username");
  page.replace("Новый пароль","New password");
  page.replace("Поиск сетей…","Scanning networks\u2026");
  page.replace("Пароль MQTT","MQTT password");
  page.replace("Диагностика","Diagnostics");
  page.replace("Пароль сети","Network password");
  page.replace(" · открытая"," \u00b7 open");
  page.replace("Устройство","Device");
  page.replace("Найти сети","Scan networks");
  page.replace("Подключить","Connect");
  page.replace("Выключена","Disabled");
  page.replace("Состояние","Status");
  page.replace("Сохранить","Save");
  page.replace("О модуле","About");
  page.replace("Прошивка","Firmware");
  page.replace("IP-адрес","IP address");
  page.replace("Включена","Enabled");
  page.replace("Главная","Home");
  page.replace("Логин","Username");
  page.replace("Порт","Port");
  return page;
}
