#pragma once
// Central web UI dictionary. Only trusted templates pass through this function.
inline String localizeWeb(String page) {
  if(!WebSettings::english())return page;
  page.replace("Показывать телеметрию","Show telemetry");
  page.replace("Выключите для просмотра медиа. Источники и сущности сохраняются, связь MQTT остаётся активной.","Turn off to view media. Sources and entities are preserved, and MQTT stays connected.");
  page.replace("Сохранить режим","Save mode");page.replace("Режим сохранён.","Mode saved.");
  page.replace("Настроить мультимедиа","Configure multimedia");page.replace("Мультимедиа","Multimedia");page.replace("Медиатека","Media library");
  page.replace("SD-карта","SD card");
  page.replace("Тест создаёт папки на SD и файл 4vrs-test.gif. Существующие файлы сохраняются.","The test creates SD folders and 4vrs-test.gif. Existing files are preserved.");
  page.replace("Свои GIF: /4vrs/animations/. До 240 × 320, 256 КиБ. Без масштабирования. Скорость зависит от сложности кадров. После перезапуска возвращается обычный режим.","Your GIFs: /4vrs/animations/. Up to 240 × 320, 256 KiB. No scaling. Speed depends on frame complexity. Restarting restores the normal mode.");
  page.replace("Тест GIF","Test GIF");page.replace("Воспроизвести","Play");page.replace("Остановить","Stop");

  page.replace("Проверка при запуске. После установки или извлечения карты перезапустите модуль. Форматирование не выполняется.","Checked at startup. Restart the module after inserting or removing a card. No formatting is performed.");
  page.replace("Карта доступна для чтения.","Card is readable.");
  page.replace("Карта не читается. Проверьте подключение и FAT32.","Card is unreadable. Check wiring and FAT32.");
  page.replace("Не удалось прочитать состояние карты.","Could not read card status.");
  page.replace("После перезапуска найдите новый IP по MAC в роутере. Если за 60 секунд новая сеть не даст IP, модуль перезапустится с прежними настройками Wi-Fi. Если прежняя сеть тоже недоступна, появится точка настройки модуля: http://192.168.4.1.","After restart, find the new IP by MAC in your router. If the new network provides no IP within 60 seconds, the device restarts with its previous Wi-Fi settings. If the previous network is also unavailable, the setup access point appears: http://192.168.4.1.");
  page.replace("Не удалось подтвердить сохранение. Если модуль перезапустился, найдите его в новой сети; иначе повторите попытку.","Could not confirm saving. If the device restarted, find it on the new network; otherwise retry.");
  page.replace("Поддерживаются сети 2,4 ГГц. После сохранения модуль перезапустится, соединение с этой страницей прервётся.","2.4 GHz networks are supported. Saving restarts the device and disconnects this page.");
  page.replace("На модуле установлен статический IP. Перед сменой сети проверьте адрес, маску и шлюз или включите DHCP.","The device uses a static IP. Check its address, mask and gateway or enable DHCP before changing networks.");
  page.replace("Настройки сохранены. Модуль перезапускается и подключается к выбранной сети.","Settings saved. The device is restarting and connecting to the selected network.");
  page.replace("Введите пароль выбранной сети. Для открытой сети оставьте поле пустым.","Enter the selected network password. Leave empty for an open network.");
  page.replace("Сети не найдены. Повторите поиск или введите SSID вручную.","No networks found. Scan again or enter the SSID manually.");
  page.replace("Не удалось выполнить поиск. Повторите попытку.","Scan failed. Please retry.");
  page.replace("Для скрытой сети введите имя вручную.","Enter the name manually for a hidden network.");
  page.replace("Сохранить и перезапустить","Save and restart");
  page.replace("Выберите сеть из списка.","Select a network from the list.");
  page.replace("Проверьте SSID и пароль.","Check SSID and password.");
  page.replace("Имя сети (SSID)","Network name (SSID)");
  page.replace("Доступные сети","Available networks");
  page.replace("Сменить Wi-Fi","Change Wi-Fi");
  page.replace("Текущая сеть:","Current network:");
  page.replace("Выберите сеть","Select a network");
  page.replace("Пароль Wi-Fi","Wi-Fi password");
  page.replace("Поиск сетей…","Scanning networks...");
  page.replace("Найти сети","Scan networks");
  page.replace("Устройство, сеть, экран и обновления","Device, network, display and updates");
  page.replace("Имя модуля","Device name");
  page.replace("Сохранить имя","Save name");
  page.replace("Имя сохранено.","Name saved.");
  page.replace("Не удалось сохранить имя.","Could not save name.");
  page.replace("<summary>Устройство</summary>","<summary>Device</summary>");
  page.replace("<summary>Сеть</summary>","<summary>Network</summary>");
  page.replace("<summary>Экран</summary>","<summary>Display</summary>");
  page.replace("Доступ и язык","Access and language");
  page.replace("<summary>Обновления</summary>","<summary>Updates</summary>");
  page.replace(">Настройки<",">Settings<");
  page.replace("← Настройки","← Settings");
  page.replace("0% выключает подсветку. Последнее изменение из web или Home Assistant сохраняется на устройстве.","0% turns the backlight off. The latest change from web or Home Assistant is saved on the device.");
  page.replace("Яркость подсветки:","Backlight brightness:");
  page.replace("Сохранить яркость","Save brightness");
  page.replace("Яркость сохранена.","Brightness saved.");
  page.replace("Не удалось сохранить яркость.","Could not save brightness.");
  page.replace("Проверьте IP, маску, шлюз и DNS. Подсеть точки настройки 192.168.4.0/24 зарезервирована.","Check IP, mask, gateway and DNS. Setup subnet 192.168.4.0/24 is reserved.");
  page.replace("После применения откройте эту страницу по новому адресу и подтвердите связь в течение 3 минут. Без подтверждения вернутся прежние настройки. Во время проверки доступна точка настройки Wi-Fi.","After applying, open this page at the new address and confirm connectivity within 3 minutes. Without confirmation, the previous settings return. Setup Wi-Fi stays available during the trial.");
  page.replace("Шлюз и DNS можно оставить пустыми для изолированной сети. Для обновлений GitHub нужны доступ в интернет и рабочий DNS.","Gateway and DNS may be empty for an isolated network. GitHub updates require internet access and working DNS.");
  page.replace("DHCP получает адрес автоматически. Для статического адреса выберите свободный IP вашей сети.","DHCP obtains an address automatically. For static addressing, choose an unused IP on your network.");
  page.replace("Проверка началась. Откройте новый адрес и подтвердите подключение в течение 3 минут.","Trial started. Open the new address and confirm connectivity within 3 minutes.");
  page.replace(" DHCP: найдите адрес в роутере или через точку настройки Wi-Fi."," DHCP: find the address in your router or through setup Wi-Fi.");
  page.replace("Ожидается подтверждение. Осталось секунд: ","Awaiting confirmation. Seconds remaining: ");
  page.replace("Настройки сети сохранены.","Network settings saved.");
  page.replace("Текущий адрес: ","Current address: ");
  page.replace("Настройки IPv4","IPv4 settings");
  page.replace("DHCP, IP, маска, шлюз и DNS","DHCP, IP, subnet mask, gateway and DNS");
  page.replace("Режим адресации","Address mode");
  page.replace("Маска подсети","Subnet mask");
  page.replace("Шлюз","Gateway");
  page.replace("Основной DNS","Primary DNS");
  page.replace("Резервный DNS","Secondary DNS");
  page.replace("Применить и проверить","Apply and test");
  page.replace("Открыть новый адрес","Open new address");
  page.replace("Подтвердить подключение","Confirm connection");
  page.replace("При нескольких комнатах показывает название и значок перед страницами каждой комнаты. Для одной комнаты заставка всегда пропускается. При отключении название остаётся в заголовке, комнаты не смешиваются.","With multiple rooms, show a title and icon before each room. A single room always skips its cover. When disabled, the room name stays in the header and rooms remain separate.");
  page.replace("Не удалось сохранить настройки экрана. Попробуйте ещё раз.","Could not save display settings. Please retry.");
  page.replace("Настройки экрана сохранены.","Display settings saved.");
  page.replace("Сохранить настройки экрана","Save display settings");
  page.replace("Показывать заставки комнат","Show room covers");
  page.replace("<h2>Экран</h2>","<h2>Display</h2>");
  page.replace("Ответ не получен. Если SDO/MISO не подключён, это ожидаемо и не означает неисправность дисплея. Иначе проверьте соединение и питание.","No response received. If SDO/MISO is not connected, this is expected and does not mean the display is faulty. Otherwise, check wiring and power.");
  page.replace("Проверка связи с контроллером дисплея по SDO/MISO (GPIO19). Для вывода изображения этот провод не нужен.","Check communication with the display controller over SDO/MISO (GPIO19). This wire is not required to show images.");
  page.replace("Ответ контроллера не подтверждает исправность матрицы и подсветки: изображение нужно оценить визуально.","A controller response does not verify the panel or backlight: inspect the image visually.");
  page.replace("Не удалось выполнить проверку. Проверьте связь с модулем и повторите попытку.","Could not run the check. Check the device connection and try again.");
  page.replace("Контроллер дисплея отвечает. Повторные чтения регистров совпадают.","The display controller responds. Repeated register readings match.");
  page.replace("Данные ещё не прочитаны. Повторите проверку после запуска дисплея.","No readings yet. Try again after the display starts.");
  page.replace("Ответы различаются. Проверьте соединения SPI и питание дисплея.","Readings differ. Check the SPI connections and display power.");
  page.replace("Нажмите кнопку для проверки.","Press the button to run a check.");
  page.replace("Проверяем связь с дисплеем…","Checking display communication...");
  page.replace("Данные дисплея (JSON)","Display data (JSON)");
  page.replace("Проверить дисплей","Check display");
  page.replace("Проверка дисплея","Display check");
  page.replace("Регистры дисплея","Display registers");
  page.replace("lang=\"ru\"","lang=\"en\"");
  page.replace("Пустой пароль сохраняет текущий. Логин: 1–32 символа, пароль: 1–64. Используйте латинские буквы, цифры и символы без пробелов; двоеточие в логине недопустимо.","Leave the password empty to keep it. Username: 1\u201332 characters; password: 1\u201364. Use ASCII letters, numbers and symbols without spaces; no colon in the username.");
  page.replace("Эти данные используются только для web-входа. Пароли OTA, Wi-Fi и MQTT не изменяются.","These credentials are only for web sign-in. OTA, Wi-Fi and MQTT passwords remain unchanged.");
  page.replace("Точка настройки отключена. Вернитесь в локальную сеть и откройте показанный IP.","The setup access point is off. Rejoin your LAN and open the displayed IP address.");
  page.replace("Первый канал HA: до 20 сущностей, по три на странице. Без данных остаётся встроенная заставка.","Display up to 20 Home Assistant entities, three per page. The default artwork is shown until data arrives.");
  page.replace("Нет связи. Проверьте сохранённые настройки после подключения.","Connection lost. Check the saved settings after reconnecting.");
  page.replace("Выберите сеть 2,4 ГГц. Для скрытой сети введите имя вручную.","Choose a 2.4 GHz network. Enter the name manually for a hidden network.");
  page.replace("Точка настройки выключится после 15 секунд устойчивой связи.","The setup access point will turn off after 15 seconds of stable connection.");
  page.replace("Вводится только в нашей интеграции HA. Не публикуйте ключ.","Enter this key in the 4VRS Display HA integration. Keep it private.");
  page.replace("Сохранено. При следующем запросе войдите с новыми данными.","Saved. Sign in with the new credentials on the next request.");
  page.replace("Связь потеряна. Откройте настройки и проверьте сохранение.","Connection lost. Open settings to check whether the changes were saved.");
  page.replace("Связь с платой потеряна. Проверьте подключение к её Wi-Fi.","Connection to the device was lost. Check its Wi-Fi connection.");
  page.replace("Настройки сохранены. Подключение выполняется в фоне.","Settings saved. Connecting in the background.");
  page.replace("Не удалось прочитать настройки. Обновите страницу.","Could not read settings. Reload this page.");
  page.replace("Принимать данные Home Assistant через MQTT","Receive Home Assistant data via MQTT");
  page.replace("Подключение к брокеру и Home Assistant","Connect to a broker and Home Assistant");
  page.replace("CA-сертификат PEM (обязателен для TLS)","CA certificate in PEM format (required for TLS)");
  page.replace("Не удалось обновить сведения о сети.","Could not refresh network information.");
  page.replace("Посмотреть изображение по умолчанию","View the default image");
  page.replace("Поиск не завершился. Повторите.","Scan did not finish. Try again.");
  page.replace("Пусто — сохранить действующий","Leave empty to keep the current password");
  page.replace("Сеть сохранена. Подключаемся…","Network saved. Connecting\u2026");
  page.replace("TLS с проверкой сертификата","TLS with certificate verification");
  page.replace("Версия, сеть и диагностика","Version, network and diagnostics");
  page.replace("Лицензия собственного кода","Own code license");
  page.replace("Удалить сохранённый пароль","Delete the saved password");
  page.replace("Последний код отключения: ","Last disconnect reason: ");
  page.replace("Управление вашим дисплеем","Manage your display");
  page.replace("Подключение интеграции HA","Pair with the HA integration");
  page.replace("Ошибка чтения настроек","Could not read settings");
  page.replace("Повторите новый пароль","Confirm new password");
  page.replace("Точка настройки Wi-Fi","Wi-Fi setup access point");
  page.replace("Обновление по воздуху","Over-the-air updates");
  page.replace("Подробная диагностика","Detailed diagnostics");
  page.replace("Сохранить подключение","Save connection");
  page.replace("Настройки интерфейса","Interface settings");
  page.replace("Пароли не совпадают.","Passwords do not match.");
  page.replace("Сеть ещё не выбрана.","No network selected yet.");
  page.replace("Открыть устройство: ","Open device: ");
  page.replace("Встроенная заставка","Default artwork");
  page.replace("Язык и данные входа","Language and sign-in");
  page.replace("Нет связи с модулем","Cannot reach the device");
  page.replace("Открыть настройки","Open settings");
  page.replace("Чтение состояния…","Reading status\u2026");
  page.replace("Ключ сопряжения:","Pairing key:");
  page.replace("Настройки · 4VRS","Settings \u00b7 4VRS");
  page.replace("Язык интерфейса","Interface language");
  page.replace("Имя сети (SSID)","Network name (SSID)");
  page.replace("Подключаемся к ","Connecting to ");
  page.replace("Найдено сетей: ","Networks found: ");
  page.replace("Настройки MQTT","MQTT settings");
  page.replace("Найденные сети","Available networks");
  page.replace("Адрес брокера","Broker address");
  page.replace("Выберите сеть","Choose a network");
  page.replace("Подключено к ","Connected to ");
  page.replace("Пользователь","Username");
  page.replace("Новый пароль","New password");
  page.replace("Поиск сетей…","Scanning networks\u2026");
  page.replace("Пароль MQTT","MQTT password");
  page.replace("Диагностика","Diagnostics");
  page.replace("Пароль сети","Network password");
  page.replace(" · открытая"," \u00b7 open");
  page.replace("Устройство","Device");
  page.replace("Найти сети","Scan networks");
  page.replace("Подключить","Connect");
  page.replace("Выключена","Disabled");
  page.replace("Состояние","Status");
  page.replace("Сохранить","Save");
  page.replace("О модуле","About");
  page.replace("Прошивка","Firmware");
  page.replace("IP-адрес","IP address");
  page.replace("Включена","Enabled");
  page.replace("Главная","Home");
  page.replace("Логин","Username");
  page.replace("Порт","Port");
  return page;
}
