#pragma once
static const char WIFI_PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wi-Fi · 4VRS</title><style>body{font:17px system-ui;max-width:640px;margin:32px auto;padding:0 20px;background:#101820;color:#edf4ff}a{color:#7ce0ff}label{display:block;margin:18px 0}input,select,button{box-sizing:border-box;width:100%;font:inherit;padding:12px;margin-top:6px}button{background:#087cba;color:white;border:0}button:disabled{opacity:.5}small{color:#bacbde}</style><a href="/settings">← Настройки</a><h1>Сменить Wi-Fi</h1><p>Текущая сеть: <strong id="current">—</strong></p><p>Поддерживаются сети 2,4 ГГц. После сохранения модуль перезапустится, соединение с этой страницей прервётся.</p><p id="static-note" hidden>На модуле установлен статический IP. Перед сменой сети проверьте адрес, маску и шлюз или включите DHCP.</p><p><a href="/network">Настройки IPv4</a></p><button id="scan" type="button">Найти сети</button><label>Доступные сети<select id="networks"><option value="">Выберите сеть</option></select></label><p id="scan-status" role="status"></p><form id="wifi"><label>Имя сети (SSID)<input id="ssid" maxlength="32" required autocomplete="off"></label><small>Для скрытой сети введите имя вручную.</small><label>Пароль Wi-Fi<input id="password" type="password" maxlength="63" autocomplete="new-password"></label><small>Введите пароль выбранной сети. Для открытой сети оставьте поле пустым.</small><button id="save">Сохранить и перезапустить</button></form><p id="status" role="status"></p><p>После перезапуска найдите новый IP по MAC в роутере. Если за 60 секунд новая сеть не даст IP, модуль перезапустится с прежними настройками Wi-Fi. Если прежняя сеть тоже недоступна, появится точка настройки модуля: http://192.168.4.1.</p><script>
const $=id=>document.getElementById(id),token='__TOKEN__';let restarting=false;
fetch('/settings/wifi/status',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(c=>{$('current').textContent=c.ssid;$('static-note').hidden=!c.static}).catch(()=>$('status').textContent='Не удалось прочитать настройки. Обновите страницу.');
$('networks').onchange=()=>{if($('networks').value){$('ssid').value=$('networks').value;$('password').value=''}};
$('scan').onclick=async()=>{if(restarting)return;$('scan').disabled=true;$('save').disabled=true;$('scan-status').textContent='Поиск сетей…';try{
let r=await fetch('/settings/wifi/scan',{method:'POST',body:new URLSearchParams({token})});if(!r.ok)throw Error();let found=null;
for(let i=0;i<30;i++){await new Promise(resolve=>setTimeout(resolve,1000));r=await fetch('/settings/wifi/scan',{cache:'no-store'});if(r.status===202)continue;if(!r.ok)throw Error();found=await r.json();break}
if(!Array.isArray(found))throw Error();$('networks').replaceChildren();let first=document.createElement('option');first.value='';first.textContent='Выберите сеть';$('networks').append(first);const seen=new Set();for(const n of found.sort((a,b)=>b.rssi-a.rssi)){if(!n.ssid||seen.has(n.ssid))continue;seen.add(n.ssid);let option=document.createElement('option');option.value=n.ssid;option.textContent=n.ssid+' ('+n.rssi+' dBm)'+(n.open?' · OPEN':'');$('networks').append(option)}$('scan-status').textContent=seen.size?'Выберите сеть из списка.':'Сети не найдены. Повторите поиск или введите SSID вручную.';
}catch{$('scan-status').textContent='Не удалось выполнить поиск. Повторите попытку.'}finally{$('scan').disabled=false;$('save').disabled=false}};
$('wifi').onsubmit=async e=>{e.preventDefault();if(restarting||$('save').disabled)return;const ssid=$('ssid').value,password=$('password').value;if(new TextEncoder().encode(ssid).length>32||(password&&new TextEncoder().encode(password).length<8)||new TextEncoder().encode(password).length>63){$('status').textContent='Проверьте SSID и пароль.';return}$('save').disabled=true;$('scan').disabled=true;try{let r=await fetch('/settings/wifi',{method:'POST',body:new URLSearchParams({token,ssid,password})});if(!r.ok)throw Error();restarting=true;$('password').value='';$('status').textContent='Настройки сохранены. Модуль перезапускается и подключается к выбранной сети.'}catch{$('status').textContent='Не удалось подтвердить сохранение. Если модуль перезапустился, найдите его в новой сети; иначе повторите попытку.';$('save').disabled=false;$('scan').disabled=false}};
</script></html>)HTML";
