from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import math,io
r=Path(__file__).resolve().parents[1];frames=[]
font=ImageFont.truetype('C:/Windows/Fonts/arialbd.ttf',30)
small=ImageFont.truetype('C:/Windows/Fonts/arial.ttf',14)
for n in range(16):
 im=Image.new('RGB',(240,320),(5,12,24));d=ImageDraw.Draw(im)
 d.text((120,40),'4VRS',font=font,fill=(0,190,255),anchor='mm')
 d.text((120,75),'GIF / SD CARD',font=small,fill='white',anchor='mm')
 for i in range(12):
  a=i*math.tau/12;v=(i-n)%12;c=(0,50+v*16,80+v*15)
  x=120+42*math.cos(a);y=170+42*math.sin(a);d.ellipse((x-5,y-5,x+5,y+5),fill=c)
 d.text((120,255),'REAL HARDWARE TEST',font=small,fill=(130,180,210),anchor='mm')
 frames.append(im)
b=io.BytesIO();frames[0].save(b,format='GIF',save_all=True,append_images=frames[1:],duration=120,loop=0,disposal=1,optimize=True)
data=b.getvalue();out=r/'assets/test';out.mkdir(parents=True,exist_ok=True);(out/'4vrs-test.gif').write_bytes(data)
(r/'firmware/rack_bootstrap/GifTestAsset.h').write_text('#pragma once\n// Generated by tools/generate_gif_test.py; real SD playback test.\nstatic const uint8_t GIF_TEST[] PROGMEM={\n'+','.join(str(v) for v in data)+'\n};\n')
print('GIF bytes',len(data))
