"""Convert the generated flat artwork to a 240x320 RGB565 flash asset. Requires Pillow."""
from pathlib import Path
import argparse
import struct
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    args = parser.parse_args()
    image = Image.open(args.source).convert('RGB').resize((240, 320), Image.Resampling.LANCZOS)
    assets = ROOT / 'assets'
    assets.mkdir(exist_ok=True)
    image.save(assets / 'demo-240x320.png')
    pixels = b''.join(struct.pack('<H', ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)) for r, g, b in image.getdata())
    (assets / 'demo-240x320.rgb565').write_bytes(pixels)
    # BMP with RGB565 masks, top-down scanlines; pixels begin at offset 66.
    bmp = (struct.pack('<2sIHHI', b'BM', 66 + len(pixels), 0, 0, 66) +
           struct.pack('<IiiHHIIiiII', 40, 240, -320, 1, 16, 3, len(pixels), 2835, 2835, 0, 0) +
           struct.pack('<III', 0xf800, 0x07e0, 0x001f) + pixels)
    (assets / 'demo-240x320.bmp').write_bytes(bmp)
    header = '#pragma once\n#include <Arduino.h>\n// Generated by tools/prepare_image.py. RGB565 pixels start at byte 66.\n'
    header += 'static constexpr unsigned DEMO_WIDTH = 240, DEMO_HEIGHT = 320, DEMO_PIXEL_OFFSET = 66;\n'
    header += 'static const uint8_t DEMO_BMP[] PROGMEM = {\n'
    header += ''.join('  ' + ','.join(f'0x{b:02x}' for b in bmp[i:i+24]) + ',\n' for i in range(0, len(bmp), 24))
    header += '};\n'
    (ROOT / 'firmware/rack_bootstrap/DemoImage.h').write_text(header, encoding='utf-8')
    # Verify dimensions, pixel order and RGB565 conversion by independently decoding the BMP.
    decoded = Image.open(assets / 'demo-240x320.bmp').convert('RGB')
    assert decoded.size == (240, 320)
    for expected, actual in zip(image.getdata(), decoded.getdata()):
        assert all(abs(a-b) <= tolerance for a,b,tolerance in zip(expected, actual, (8,4,8)))
    print(f'Validated RGB565: {len(pixels)} pixel bytes; {len(bmp)} embedded bytes.')

if __name__ == '__main__':
    main()
